name: Deploy

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  test:
    uses: elvisperlika/PPS-24-Skalamon/.github/workflows/sbt-test.yaml@ci-setup

  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'sbt'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Build JAR
        run: sbt package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skalamon
          path: target/scala-3.3.6/*.jar

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          files: target/scala-3.3.6/*.jar